# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # image: ghcr.io/mihnita/okapi:latest
      image: us-docker.pkg.dev/android-emulator-268719/images/r-google-x64:30.0.23
    steps:
    - uses: actions/checkout@v3

    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: /root/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: test

    - name: "Run UI Tests"
      uses: vgaidarji/android-github-actions-emulator@v1.0.1

    - name: Build with Maven
      run: |
        echo ==== VERSIONS ==========
        echo $PWD
        echo ========================
        set
        echo ========================
        ls -ali
        echo ========================
        find /
        echo ========================

